### ISSUE TITLE
[META] Rethink/redesign various elements for mobile.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#197]
Here's what it looks like currently:

![backdropcms org-mobile_version](https://cloud.githubusercontent.com/assets/2423362/13895742/d56d790c-edcb-11e5-8abe-03d639a889e9.png)

...quite a few issues here:

- [ ] Too long, so too much scrolling. I'm not sure what we can actually do about it (perhaps use the already ported [Back To Top](https://backdropcms.org/project/back_to_top) would be an improvement), but...

- [ ] ...having the sidebar after the main content might be a general trend and good practice, but definitely not when its the place where the main navigation is. We need to have a mobile version of the main nav menu and while that might take some time to draft and implement, [Responsive Menus](https://backdropcms.org/project/responsive_menus) or [Mobile Navigation](https://backdropcms.org/project/mobile_navigation) might be a good solution to use in the meantime.

- [ ] Also, when the sidebar menu switches to mobile but still not too narrow (think iPads and other tablets), there is so much waste of space there:

![backdropcms org-mobile_version-menu_sidebar-waste_of_space](https://cloud.githubusercontent.com/assets/2423362/13896422/c73159d6-edde-11e5-83a8-3a48645dcc63.png)

- [ ] There is an issue with the "Show your support" form (shown only to registered and logged in users) where the "Your logo" field is shorter than the rest and so the upload button is mostly hidden:

![backdropcms org-show_your_support_form-upload_logo_button_not_visible](https://cloud.githubusercontent.com/assets/2423362/13895903/dd5717b0-edce-11e5-84e7-5af87d135480.png)

- [ ] This won't save much vertical space, but we seem to wrap the two "download" and "pantheon" buttons sooner than hiding the nav bar:

![backdropcms org-buttons_horizontally_aligned](https://cloud.githubusercontent.com/assets/2423362/13895989/afab5090-edd0-11e5-9595-0e0d4b0dd7d2.png)

![backdropcms org-buttons_vertically_aligned-sidebar_still_visible](https://cloud.githubusercontent.com/assets/2423362/13895991/afb47422-edd0-11e5-9b2a-279248f001e4.png)

...so when we reach the breakpoint where we push the sidebar down the page, we still show the two buttons vertically stacked despite the fact that there is enough space to have them aligned horizontally:

![backdropcms org-buttons_vertically_aligned-sidebar_not_visible](https://cloud.githubusercontent.com/assets/2423362/13895990/afb1586e-edd0-11e5-87f9-c6f3dc8cd324.png)

I know there wouldn't be much vertical space gain, but still.
