### ISSUE TITLE
[Meta] Allow voting (5 star) and leaving feedback on projects from backdropcms.org.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#246]
Ideas from the [Firefox Addons](https://addons.mozilla.org/firefox/) and the [Chrome Extensions](https://chrome.google.com/webstore/category/extensions) sites...

- [ ] "Leave feedback link" (ideally open in a modal so that there is no additional page loads) in project node and project views listings.
- [ ] [Five Star](https://github.com/backdrop-contrib/fivestar) field(s) - we could have a single one or separate for features/UX/support.
- [ ] Feedback/comment textbox.
- [ ] Show average rating value (five star image) + number of ratings in project node and project views listings
- [ ] Show average rating value (five star image) + number of ratings in Project Installer UI and allow voting/feedback from it (???).
- [ ] Show a "Featured Projects" section with highly rated ones in the "Extend Backdrop" page (???).
- [ ] Show a "Popular Projects" section with most downloaded/used ones in the "Extend Backdrop" page.
- [ ] Show a "Fresh/Upcoming Projects" section with new ones (by initial release date) in the "Extend Backdrop" page.
- [ ] "Pick of the week/moth project" header in the "Extend Backdrop" page (could calculate something combining most downloads, most comments and rating).
- [ ] Organize a group of people that write reviews/showcases/walk-throughs of pick-of-the-week/moth projects:
  - @klonos
  - ???
- [ ] ???

**Comment by jenlampton** [comment]
Adding the `audience - marketing` tag because "Pick of the week/moth" sounds like something we need for community outreach :)

**Comment by jenlampton** [comment]
I'm not sure how I feel about 5-star voting. the 5-stars are pretty, but over time pretty much everything ends up with a 3.5 star review. Numbers like downloads and active installs have a lot more meaning to people than a star rating. Only the most motivated people (both good and bad) will take the time to leave ratings. Usage statistics require no action.

Feedback is also an interesting idea, but keep in mind that feedback for apps has turned into an issue queue. If there was a way we could automate a post into the project's GitHub issue queue via this modal, then okay, I could see that. But I don't think splitting developer focus between feedback on b.org and issues on GitHub is a good idea.

I love featured / popular / fresh sorts on the modules/themes/layouts pages. and I love, love, LOVE, Pick of the week/month project idea :)

**Comment by amilenkov** [comment]
I have done sites with this very useful petition module and it can be used in a way every member of community can start petition asking for some development and other can subscribe. D6 version works fine, D7 is only dev version and get some errors after install but there is a manual fix and I have it somewhere saved. 
https://www.drupal.org/project/petition_node

Next poll module give voters option to change their votes if they change their opinion. If start discussion on some feature people may change their mind as result of discussion and this can help to see how community attitudes to an issue is changed through time.
https://www.drupal.org/project/advpoll
This requires voting api but this port is already started:
https://github.com/backdrop-contrib/votingapi

*  *  *
Statistic of installed modules don't tell you what people thing of these modules and if they expect any improvements; why they do not install other modules.

**Comment by izmeez** [comment]
It would be nice to have a ratings and comments block on the project pages like Wordpress plugins have. It's hard to know where else would be a good place to highlight the usefulness of different modules & themes. I agree the statistics don't show what people think or how they use the modules. The comments might resonate or raise a new thought or approach.

**Comment by jenlampton** [comment]
I do like the idea of allowing comments on the modules.

I would also like us to evaluate the other kinds of ratings to see if there might be something else that's a better fit than 5-star. Maybe just a vote-up/vote-down would work better? The only problem with comments is that they require a lot more work from people. Something like a 5-star or thumbs-up rating would be really easy for people to provide, and I think we'll get a lot more data more quickly. I'll create a separate issue where we can discuss this one item in more detail.

I've attempted to re-organize the items in the original post to separate them into smaller more concrete tasks, and organize them based on where the changes need to happen (pages on b.org, project browser, core, etc)
