### ISSUE TITLE
[META] Theme todos arising from layouts redux

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#361]
- [x] Maximum length for a 'line of text' (should be ~100 characters / 680px)
- [x] Background colors on modules/themes/layouts pages need to be flipped (gray at the top)
- [x] Custom preprocessing for showcase node kept intact
- [x] Handbook sidebar should resemble user guide sidebar (and be on right)

**Comment by jenlampton** [comment]
I removed the left sidebar from the default layout and added the Book content type into the layout for User Guide, and that solved the style issue for the sidebar menu style. If there is any CSS specific to that block it may still need to be removed. (Noting here for future reference.)

**Comment by jenlampton** [comment]
Pushed the latest code live, closing this issue.
