### ISSUE TITLE
[META] Build backdropcms.org on Backdrop

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#38]
With the imminent release of Backdrop 1.0.0 we should also move the official website to Backdrop to demonstrate that we have confidence on the release.

The following are things that need to be done as part of the port to Backdrop CMS:

contrib modules (moved into Backdrop core):
- [x] admin_menu (since Backdrop 1.0.0 | [#189](https://github.com/backdrop/backdrop-issues/issues/189))
- [x] ctools (since Backdrop 1.0.0 | [#136](https://github.com/backdrop/backdrop-issues/issues/136), [#138](https://github.com/backdrop/backdrop-issues/issues/138))
- [x] views (since Backdrop 1.0.0 | [#40](https://github.com/backdrop/backdrop-issues/issues/40))

contrib modules (we need to port):
- [x] [codefilter](https://github.com/backdrop-contrib/codefilter) | https://www.drupal.org/project/codefilter
- [x] [devel](https://github.com/backdrop-contrib/devel) | https://www.drupal.org/project/devel
- [x] [formblock](https://github.com/backdrop-contrib/formblock) | https://www.drupal.org/project/formblock
- [x] [link](https://github.com/backdrop-contrib/link) [#240](https://github.com/backdrop/backdrop-issues/issues/240) (target for Backdrop core [1.2.0](https://github.com/backdrop/backdrop-issues/milestones/1.2.0)) | https://www.drupal.org/project/link
- [x] [on_the_web](https://github.com/backdrop-contrib/on_the_web) | https://www.drupal.org/project/on_the_web
- [x] [redirect](https://github.com/backdrop-contrib/redirect) | https://www.drupal.org/project/redirect
- [x] [special_menu_items](https://github.com/backdrop-contrib/special_menu_items) | https://www.drupal.org/project/special_menu_items

contrib modules (we can launch w/o these)
- [x] honeypot
- [x] search_config
- [x] [googleanalytics](https://github.com/backdrop-contrib/googleanalytics) | https://www.drupal.org/project/google_analytics
- [x] flexslider (this is built right into the theme currently)

theme & layout
- [x] port backdropcms theme / build new brorg theme
- [x] create new custom double_fixed layout
- [x] add fancy js layout drawer toggle in borg theme

**Comment by quicksketch** [comment]
Thanks for opening this @klonos. We should definitely move the main site over to Backdrop ASAP. Our contrib modules include:

- Link
- Code Filter
- Font Awesome
- Form block
- On The Web
- Redirect
- Special menu items
- Search Configuration
- Honeypot
- Google Analytics
- Views Slideshow

We've got a half-dozen others but they've been merged into core.

I think we should pursue the porting ASAP and do the contrib conversions as we go along. I don't think any of these modules have been started porting yet, but with our already growing list of contrib authors, we don't know which ones have been started until they file an application or check in the initial version.

**Comment by klonos** [comment]
..turned this to a meta in order to sort of "track" progress. The reason I say "sort of" is because although the progress will show as x out of y tasks completed, some modules will be harder (and more time consuming) to get ported than others.

**Comment by docwilmot** [comment]
> I think we should pursue the porting ASAP and do the contrib conversions as we go along

I thought this implied we should port the *site* ASAP and port the contrib modules as we go along. Besides, none of these modules seem like they would be absolutely essential. Porting the site should be relatively simple, since it is not very complex, yet. 
I'd also add to the list, port the theme, whatever it is.

**Comment by quicksketch** [comment]
After the success of porting the API site, I'm going to start porting the main site. If anyone is interested in accelerating the work, the most helpful thing would be a port of Link, Redirect, and Special Menu Items. The other modules can be avoided entirely or substituted by a small amount of work in the theme.

**Comment by docwilmot** [comment]
Woohoo! Having some cholesterol now. Will check which one I can manage later.

**Comment by docwilmot** [comment]
Can we get some idea of your thoughts for the design and organization?

**Comment by docwilmot** [comment]
tried a start wit special menu items. Stuck on the fact that it depends on an override of theme_link(). Unfortunately that seems to be no longer called by l() (and in fact I dont see theme_links called anywhere. 
Not sure if there is another approach I could try; ideas welcomed.

**Comment by quicksketch** [comment]
> I tried a start with special menu items. Stuck on the fact that it depends on an override of theme_link(). Unfortunately that seems to be no longer called by l() (and in fact I dont see theme_links called anywhere).

Although I think we killed theme_link(), we replaced it with menu-specific theming. It looks like `menu_tree_output()` provides two options:

- theme_menu_link()
- theme_menu_tree()

Each also takes suggestions for the menu name (e.g. `theme_menu_link__navigation()`). For blocks, you could also use `hook_block_view_alter()` to alter the menu tree, but that wouldn't work in non-block situations (though menus are always in blocks now, so... maybe it would be okay).

**Comment by docwilmot** [comment]
Just in time for Superbowl https://github.com/backdrop-contrib/special_menu_items

**Comment by quicksketch** [comment]
LOL

@docwilmot++

**Comment by docwilmot** [comment]
Attempted to port Link https://github.com/docwilmot/link
It wont show in the field list at manage fields, no matter how much I ask. 
I give up; maybe someone can run with what I've got so far.

**Comment by quicksketch** [comment]
Hi @docwilmot! I'll see if I can figure out what's wrong and post in your sandbox. Thanks!

**Comment by docwilmot** [comment]
Seems @biolithic has ported Link and is almost ready with redirect. https://github.com/backdrop-ops/contrib/issues/50

**Comment by biolithic** [comment]
Yes @docwilmont, I saw that need and will be getting around to redirect
possibly tonight so hopefully the site can use them this weekend.

**Comment by klonos** [comment]
...updated the issue summary with links to projects or issues in backdrop contrib as well as the respective projects in d.org.

**Comment by jenlampton** [comment]
The [googleanalytics](https://github.com/backdrop-contrib/googleanalytics) port could use some work.  I managed to get it converted to CMI, but had to stop there. We need to replace hook_page_alter with preprocess, if someone wants to take over from here that would be awesome :)

**Comment by quicksketch** [comment]
@jenlampton and I have made tremendous progress on this port. The upgrade overall has gone swimmingly. There were a few issues with On The Web and Form Block changing block deltas without an upgrade path, but simply replacing the blocks solved the problem.

I've pushed up our in-progress site at https://new.backdropcms.org/

Google Analytics we can work-around by simply injecting into the page template. I think our biggest "real" holdup is Redirect module, which we need for a ton of URLs we've moved around already. @biolithic had mentioned he'd started a port in https://github.com/backdrop-ops/contrib/issues/50, but the link seems dead. So if any contrib authors (current or future) want to port Redirect, I think that's our hold-up.

Please try out the new site and post here any *regressions* from the old site. If both the old and new site have the same problem, just file an entirely new issue.

**Comment by docwilmot** [comment]
Nice, BUT.
I was hoping you were doing a whole new theme. I had such dreams...

Anyway the drawer thing for the handbook desnt have a scrollbar, I cant see anything below "Developer docs"

**Comment by klonos** [comment]
> ...the drawer thing for the handbook desnt have a scrollbar

It has for me in firefox 38.0a1 x64 on Windows 8.1 as well as in Chrome 40 (I have less toolbars and thus more vertical space, but if I resize the window, the scrollbar is there). Same as Chrome with IE11.

> I cant see anything below "Developer docs"

"Developer docs" is the last item in the drawer. What did you expect past that?

**Comment by docwilmot** [comment]
:)
> "Developer docs" is the last item in the drawer

Thats probably why theres no scrollbar then!
The old site the drawer is longer so the scrollbar is persistent. Moving along then. Thanks.

**Comment by klonos** [comment]
> Thats probably why theres no scrollbar then!

:smile:

**Comment by biolithic** [comment]
Hi, nice new site.  I did not want to clutter the namespace when I see:

https://github.com/serundeputy/redirect

so I took mine down.  Don't want to have multiple copies of the same module
confusing everyone.

Let me know if it doesn't work for you, otherwise go serundeputy!

**Comment by kreynen** [comment]
Missing Backdrop header in mobile width on new site.

![selection_015](https://cloud.githubusercontent.com/assets/385234/6229868/1613b78c-b678-11e4-8bf9-33042ac514c7.png)

**Comment by quicksketch** [comment]
>  I was hoping you were doing a whole new theme. I had such dreams...

The theme is getting a very slight refresh (as seen in @kreynen's screenshot), based on newer designs from @dariusgarza. But for the most part that just means font adjustments, adding a few new design elements, and polishing the existing theme, rather than make a new one entirely. It's unlikely we'll start on a new one, but if you have suggestions Darius may be able to integrate them.

> Missing Backdrop header in mobile width on new site.

Thanks @kreynen! I hadn't noticed that problem.

Any other feedback is welcome. And if anyone is interested in helping on the site, we can get you access to the server to get a database dump and the config files. The code is simply in this repository in the "backdrop" branch: https://github.com/backdrop-ops/backdropcms.org/tree/backdrop.

**Comment by serundeputy** [comment]
@jenlampton , @quicksketch there is a port of `search_config` here:
https://github.com/backdrop-contrib/search_config

there are some issues with the CMI export.

**Comment by quicksketch** [comment]
Thanks @serundeputy!

**Comment by docwilmot** [comment]
> It's unlikely we'll start on a new one, but if you have suggestions

I always assumed this theme was temporary.

1. That design works well for a display site with a few links but will it scale well for the main hub of a major CMS? The left side menu is nearly full and there are practically no possibilities for panels and those horizontal layers of additional info in vogue in contemporary sites. Where eventually will we be putting links to forums; "sites designed with Backdrop", latest news, downloads, uploads, T-shirts, etc etc? We cannot cram all of this into the handbook drawer!?

1. The drawer thing is a bit old; cramps up my horizontal space; and works poorly on mobile (I dont like that it is at the bottom of the page).

1. The site may [unfriendly](https://github.com/backdrop-ops/backdropcms.org/issues/18#issuecomment-70584806) to new users and non-techie folk. Probably mainly because it is too different; probably its a bit stark; probably because of the second point above. A bit of color, a pic of the Dragon Drop against a blue sky. A pic of @quicksketch with a big smile, etc.

1. It may suggest that this is what Backdrop sites will look like, which may further alienate potential users (weak point I know, but bear with me, I'm listing all my gripes once and for all)

Finally I just realized that my issues would mainly be solved by NOT having the left side vertical menu with its annoying drawer.

![fin](https://cloud.githubusercontent.com/assets/1042283/6266905/0418655a-b80d-11e4-82d3-50f8cb63cde6.png)

**Comment by klonos** [comment]
> I always assumed this theme was temporary.

Me too. Loose the drawer +a mil.

**Comment by quicksketch** [comment]
Thanks guys, great feedback @docwilmot. @dariusgarza is focused primarily on the styleguide at the moment, but that's nearly complete. We're about to have to figure out exactly some of the problems mentioned, since we'd like to get a contrib project listing on the site in the very near future. The site showcase probably won't be far behind.

**Comment by quicksketch** [comment]
I got @serundeputy's port of Redirect up and running on the site, as well as our new-ish port of Google Analytics.

The only module we're missing now is Honeypot, but we should be able to transition to using the existing Captcha + Recaptcha modules without much trouble. We're looking really good!

On the theme, we'll probably proceed with the current design and evolve it as we go. Just getting our site onto Backdrop will be a big help and move forward other priorities, like getting our project browser and packager ready. We haven't yet discussed a theme change with Darius; he's still finishing our (awesome) styleguide.

**Comment by cellear** [comment]
I have some bandwidth available, and this issue seems like a good spot.  I can take a stab at porting honeypot, or I'm willing to do whatever else needs doing.

**Comment by quicksketch** [comment]
Sure @cellear, Jen and I will be at SANDCamp over the weekend. I think we'll be able to launch the site next week whether Honeypot gets updated or not, but having it working (with an upgrade path) would be the easiest thing to smooth the transition.

**Comment by jenlampton** [comment]
@cellear I believe someone is already porting honeypot.  Please check the drupal.org issue queue so we don't duplicate work!

**Comment by cellearberkeley** [comment]
Apparently boehmrya is:
https://www.drupal.org/node/2416477

I don't see it in contrib yes. My port seems to work if we need it.

I guess I'll go back to working on Feeds :)

**Comment by cellear** [comment]
Apparently boehmrya is:
https://www.drupal.org/node/2416477

I don't see it in contrib yes. My port seems to work if we need it.

I guess I'll go back to working on Feeds :)

**Comment by quicksketch** [comment]
Yay, Honeypot is finished too. Other than some minor upgrade issues, it seems to be working. We'll try to finish this up over the weekend.

**Comment by dariusgarza** [comment]
Stark, unconventional, unfriendly....all valid feedback. That's definitely not the impression that we want the site to give in the long run. 

We didn't take the standard waterfall approach to the backdropcms.org site when we started. Instead we conceived of the project as a living entity that will grow alongside the CMS and the community around it. 

The site that exists today is essentially a functional wireframe intended primarily for a development audience. Good developers are lazy and want instant, uncluttered access to information, tools and resources. They are more concerned with function than fancy. 

The sliding drawer was designed to facilitate the handbook by making the dense library of documentation easily navigable. It's meant more as an information tool, rather than a traditional sub-navigation system. I don't think we've done any formal user testing, but I personally find the drawer functionality quite handy when using the handbook as a site building reference. Analytics from other projects i've worked on have shown that many developers work on multiple, high resolution screens with lots of real estate. 

Developers are obviously not the only Backdrop audience, but we felt that in the project's nascent stages, it was most important to try to reach out to them first. As for mobile, well...give us time ;)

The backdropcms.org site will change dramatically over time. Any and all feedback is always much appreciated and the way the site is designed will ultimately make it easier to address concerns as they arise. 

d.
@docwilmot @klonos @jenlampton @quicksketch

**Comment by docwilmot** [comment]
well said. appreciated.

**Comment by quicksketch** [comment]
Thanks @dariusgarza for posting your response. We've definitely got some room to grow, but I'm quite happy with the site we have today.

Darius gave the site another design review today, and after some minor adjustments, we're happy to announce that we've flipped site.

We're live! https://backdropcms.org is now on Backdrop!

You heard it here first. :wink:

Please post here with any feedback on first impressions, or of course [file an issue against backdropcms.org](https://github.com/backdrop-ops/backdropcms.org/issues/new).

**Comment by dariusgarza** [comment]
🎏🎆🎈🎈🎈

**Comment by cellear** [comment]
Woo-hoo!  A big moment. One of many...

**Comment by docwilmot** [comment]
And, I hate to be wrong, but well done on the 'minor adjustments', because the site looks great. Very slick.

**Comment by quicksketch** [comment]
Yay! Yeah, using the right fonts really made a dramatic difference. And we'll still be improving as we go. Thanks @docwilmot. :smile:

**Comment by jenlampton** [comment]
17 out of 17 tasks done, closing this issue :)  Go team!
