### ISSUE TITLE
[META] Document upgrade paths for modules now integrated into core

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#527]
* [ ] Admin Menu (moved into core, renamed to Admin Bar module in v1.0)
* [ ] Block Class (integrated into System module in v1.0)
* [ ] Blockify (added page elements as blocks in v1.7)
* [ ] Btester Custom Block Content* (added hero block in v1.5 and contact block in v1.12)
* [ ] Caption Filter (integrated into CKEditor module n v1.2)
* [ ] Chaos Tools (integrated into various System modules in v1.0)
* [ ] CKEditor (moved into core in v1.2)
* [ ] CKEditor Link (internal link option added to CKEditor in v1.7)
* [ ] CKEditor Media Browser* (browser added to CKEditor in 1.11)
* [ ] CKEditor Upload (image uploads included as of v1.0, file uploads as of v1.10)
* [ ] Comment Closer (merged into Comment module in v1.10)
* [ ] Contact Block (contact block added in v1.12)
* [ ] Context (replaced by Layout "contexts" in v1.0)
* [ ] Date* (partially moved into core in v1.2 - Date Repeat remains in contrib)
* [ ] Diff* (diff engine included as part do Configuration Management in v1.0)
* [ ] Direct Upload (added better image/file upload options in v1.7)
* [ ] Display Suite (replaced by Layout module in v1.0)
* [ ] Elements (integrated into System module in v1.0)
* [ ] Email (moved into core in v1.2)
* [ ] Email Registration (feature included since v1.0)
* [ ] Entity API (merged into System module in v1.0)
* [ ] Entity View Mode (merged into Field UI module in v1.6)
* [ ] Features* (partially replaced by Configuration Management in v1.0)
* [ ] Field as Block (per-field blocks were added in v1.3)
* [ ] File Entity* (partially integrated into File module in v1.0 + v1.6)
* [ ] HTML5 Tools (integrated into System modules in v1.0)
* [ ] Image Mobile Camera (support to upload images via mobile cameras was added in v1.4)
* [ ] IMCE WYSIWYG Bridge (replaced by CKEditor and System module in v1.2)
* [ ] Insert (integrated into CKEditor module in v1.2)
* [ ] Instant Filter (integrated into System modules in v1.0)
* [ ] jQuery Update (not needed, Backdrop keeps jQuery 1.x up to date, with plans to upgrade to 2.x/3.x eventually)
* [ ] Libraries API (deprecated, libraries in Backdrop are bundled into modules)
* [ ] Link (moved into core in v1.2)
* [ ] Live Preview (better content preview added in v1.11)
* [ ] Menu Block (integrated into System & Menu modules v1.5)
* [ ] Menu Translation (menus became translatable in v1.10)
* [ ] Module Filter* (partially integrated into System module in v1.0)
* [ ] Nice Menus (replaced by System menus in v1.5) -- uninstall / reconfigure
* [ ] Node Block (provided by Node module in v1.5)
* [ ] Options Element (integrated into Field module in v1.12)
* [ ] Page Preview* (better content preview added in v1.11)
* [ ] Panels (replaced by Layout module in v1.0)
* [ ] Panels Everywhere (replaced by Layout module in v1.0)
* [ ] Pathauto (integrated into Path module in v1.1)
* [ ] Project Browser (integrated into System module in v1.4)
* [ ] Radix Layouts* (10 of the Radix layouts were added to core in v1.4)
* [ ] Redirect (moved into core in v1.4)
* [ ] Role Assign (integrated into User module in v1.6)
* [ ] Scheduler (merged into node in v1.10)
* [ ] Smartmenus  (replaced by System menus in v1.5 + v1.6) -- uninstall / reconfigure
* [ ] Strongarm (replaced by Configuration Management in v1.0)
* [ ] Superfish Menus (replaced by System menus in v1.5)
* [ ] Token (integrated into System module in v1.1)
* [ ] Transliteration (integrated into System module in v1.3)
* [ ] Media* (partially replaced by CKEditor and System modules in v1.0)
* [ ] Variable (replaced by Configuration Management in v1.0)
* [ ] Vertical Tabs Responsive (vertical tabs were made responsive in v1.2)
* [ ] Views (moved into core in v1.0)
* [ ] Views Bulk Operations (integrated into System modules in v1.0)
* [ ] Views Responsive Grid (Views grids use CSS Grid as of v1.12)
* [ ] WYSIWYG (replaced by CKEditor module in v1.2) -- uninstall / reconfigure

**Comment by jenlampton** [comment]
Posted this in the wrong queue, See https://github.com/backdrop/backdrop-issues/issues/3680

**Comment by jenlampton** [comment]
Turned this issue into documentation meta, re-opening.
