### ISSUE TITLE
[Meta] BLIVE - Planning for Backdrop CMS LIVE event on Sept 18th and 19th, 2020

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#692]
We had the [first planning meeting](https://docs.google.com/document/d/1sx8pDjXcrSclmOCXvEZK4HUNP87d35CDcnTrMJREjzw/edit) for our first full day Backdrop CMS only event today. Creating this as a meta issue to link to all the individual tasks that we need to complete. 

**Current plans:**

Plans are for this to be a mostly "unconference" event. We may schedule topics in advance, but are focusing on discussions over prepared presentations. There is still an opportunity to schedule some prepared presentations for those who prefer that format.

Date: Sept 18 - 19
TIME: (undecided)

Registration = $20/€15 suggested donation (nothing is required)
Day 1 (Sept 18th) = Scheduled discussion topics with assigned facilitators/experts available to answer questions?
Day 2 (Sept 19th) = Community Day - contribution and community discussions on whatever topics folks are interested in

**Topics for discussion:**

- #693 - Work with Software Freedom Conservancy to determine best method of payment
- #695 - Social Media Promotion
- #697 - What should the schedule look like?
- #700 - Website

**Things to do for event:**

- [ ] Registation form
- [ ] #694 - Blog post announcing event
  - [x] Save the date post 
  - [ ] Announce Registration 
- [ ] Schedule Social Media posts that will appear during the event
  - [ ] Schedule Twitter posts
  - [ ] Schedule Facebook posts
- [ ] Schedule volunteers 
- [ ] #701 - Graphic or Logo
- [ ] #698 - Schedule social events
- [x] Create a Zulip stream dedicated to event planning (Discussed in 8/20/20 meeting)
