### ISSUE TITLE
[META] Various types of landing pages

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#897]
We have several issues addressing landing pages, I'm going to aggregate them here:
- [ ] [Products and Orgs that support backdrop](https://github.com/backdrop-ops/backdropcms.org/issues/598)
- [ ] [Audience Personas (types of people) who use backdrop](https://github.com/backdrop-ops/backdropcms.org/issues/484)
- [ ] Audience Institutions (types of orgs)
