### ISSUE TITLE
[META] Features missing from Project Search Pages

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdropcms.org#95]
## Modules Listing Page:

- [ ] https://github.com/backdrop-ops/backdropcms.org/issues/96 "More Info about Modules" link - link to https://api.backdropcms.org/modules
- [ ]  https://github.com/backdrop-ops/backdropcms.org/issues/169 "Filter" Dropdown, suggested filters are module 'packages' from info file: like Administration, Education, Commerce, etc
- [ ] https://github.com/backdrop-ops/backdropcms.org/issues/170 "Sort" Dropdown, some example sorts are: Most Relevant, Most Downloads
- [ ] "Downloads" stat
- [ ]  "Active Installs" stat

![image](https://cloud.githubusercontent.com/assets/5607236/9532159/d483a8a8-4cd7-11e5-9aa2-e26acd4d552c.png)

## Module Page

- [ ]  Primary Download link - this is *kind of there*, I'm hacking a release table to make it look like the mock. Think we should have a primary link at the top and a release table with multiple options below the README (for mobile) and the flyout for desktop
- [ ]  Right sidebar
  1. Version/See all verions bit
  1. Downloads / Active Installs / Total Installs stats
  1. Github links
  1. Clone URL
  1. Categories
- [ ]  Versions flyout
- [ ]  Remove tabs from current modules page (View and Releases)
![image](https://cloud.githubusercontent.com/assets/5607236/9532328/0b65a41a-4cd9-11e5-8d2d-c2ca14c8738c.png)

## Themes
![themes landing featured 1x](https://cloud.githubusercontent.com/assets/5607236/9538904/e3e1eb8a-4d17-11e5-8dd3-7c8e27ce06ba.png)

- [ ]  Need ability to add a thumbnail to themes
- [ ]  Figure out how to pull contributor(s) in a sane way
- [ ]  Tabbed page view with tabs that have filters
  1. Ability to filter by theme type (Scaffolding vs Design)

![image](https://cloud.githubusercontent.com/assets/5607236/9532598/9cecc1f6-4cda-11e5-8718-91dbfd69d42c.png)

**Comment by jenlampton** [comment]
> "More Info about Modules" link - do we already have or do we need a page to explain modules in detail? 

We were going to link this to this page:
https://api.backdropcms.org/modules

**Comment by docwilmot** [comment]
> "Filter" Dropdown, suggested filters are module 'packages' from info file: like Administration, Education, Commerce, etc

> Need ability to add a thumbnail to themes

> Figure out how to pull contributor(s) in a sane way

> Ability to filter by theme type (Scaffolding vs Design)

We'll have issues with all of the above. Discussed over here: https://github.com/backdrop-ops/backdropcms.org/issues/8#issuecomment-93996583
- "Packages" are useless; 
- thumbnails are limited to one tiny thing; it was proposed (can't find the issue) to consider `preview[] = path/to/preview.png` to enable multiple previews with proper sized images; 
- there is no way to get the project author from GitHub since all projects have "backdrop-contrib" as the author; 
- similar issue as modules for theme categories.

We'll need info files to start providing a lot more info that they currently do. 

I have a PR for adding `tags[] = xxx` to modules but I think its been relegated to Backdrop 2.0, although I think it wouldnt change anything much since tags = package really.

I know its a lot to ask, but I wonder if we should consider starting this extra `.info` data now, rather than having to convert again later. I don't see how we can get the functionality @wesruv is suggesting without that being done.

**Comment by wesruv** [comment]
These are @dariusgarza's wonderful designs, he can speak to intention better than I can :package: 

It's also likely I'm not remembering everything we talked about in review of these, so don't take my descriptions above as gospel :)

I think it's safe to say we can put off parts of the design or update the design depending on what's plausible. We'll just need to hash out what we've got and how we can make a good user experience out of that. 

If we find that the 'project search' is lacking after that process THEN we can work out how we can get better data to make a better UX.

**Comment by docwilmot** [comment]
I should have said the design ideas are excellent, and I agree the aim of this is to work on the design. Post was just to raise awareness that we don't have access to the data to put into these designs, and probably won't without some other work. Agreed of course that this must go ahead with what we've got.

**Comment by klonos** [comment]
> - "Packages" are useless;

I don't want to get us -yet again- into an endless bike-shading discussion, but since we did implement https://github.com/backdrop/backdrop-issues/issues/494, we might as well provide some similar way of browsing modules by package/category ...helps newcomers a great deal. Especially when we reach a module count of 100s or 1000s.

**Comment by klonos** [comment]
> - thumbnails are limited to one tiny thing; it was proposed (can't find the issue) to consider ```preview[] = path/to/preview.png``` to enable multiple previews with proper sized images;

https://github.com/backdrop/backdrop-issues/issues/1127

**Comment by klonos** [comment]
...and yes! ...excellent designs!

> ...this must go ahead with what we've got.

I fully agree on this one too.

**Comment by clickbox** [comment]
the search bar doesn't seem to work very well. At least for when i search for the "libraries" module. Maybe I'm just hella lazy but I wish it scrolled down to the module.

**Comment by clickbox** [comment]
backup and migrate doesn't show up at all. something is wrong with the search?

**Comment by klonos** [comment]
Yeah, I confirm that while [searching for "libraries"](https://backdropcms.org/modules?keys=libraries) should bring the [Libraries](https://backdropcms.org/project/libraries) module as the first result, it lists it as last instead (perhaps the filter is set to reverse order or something)?

The list of results seem completely random and does not make any obvious sense whatsoever. It is not alphabetical for one thing.

**Comment by klonos** [comment]
[searching for "migrate"](https://backdropcms.org/modules?keys=migrate) to [for "backup"](https://backdropcms.org/modules?keys=backup) brings [Backup and Migrate](https://backdropcms.org/project/backup_migrate) as the sole result (expected I guess), but [searching for "backup migrate"](https://backdropcms.org/modules?keys=backup+migrate) or [for "backup and migrate"](https://backdropcms.org/modules?keys=backup+and+migrate) brings no results??

**Comment by clickbox** [comment]
yes, I thought I had a typo at first.

**Comment by klonos** [comment]
Filed a separate bug report for the search issue. It needs to be fixed ASAP!

**Comment by xmacinfo** [comment]
Interesting discussion! It is nice to see the module pages taking form.

**Comment by serundeputy** [comment]
>"Packages" are useless;
thumbnails are limited to one tiny thing; it was proposed (can't find the issue) to consider preview[] = path/to/preview.png to enable multiple previews with proper sized images;
there is no way to get the project author from GitHub since all projects have "backdrop-contrib" as the author;
similar issue as modules for theme categories.

Much of this information can be obtained through the the github API (https://developer.github.com/v3/#current-version) for example:

Project info for webform: https://api.github.com/repos/backdrop-contrib/webform
Release info for webform: https://api.github.com/repos/backdrop-contrib/webform/releases

There is a rate limit on github API requests 5000/hr (https://developer.github.com/v3/#rate-limiting), but we could authorize an a token and write a module that polls the github API say once per day and take the info and update the project nodes.

No need to add all the additional store in *.info files I don't know if that is better or worse, but would allow the .info files to stay as simple as possible.

**Comment by jenlampton** [comment]
hm. I like this @serundeputy!

**Comment by docwilmot** [comment]
Thanks, @serundeputy for that, didnt know you could get all that from the API. Re my statements, I still stand by most of that though.

- "packages are useless" was a bit harsh. That statement was influenced by the suggestion to kill packages and replace them with tags, thus allowing themes and layouts to also have "packages", and allowing multiple categories for modules. There's no simple solution for the former.
- would still be unable to have only one thumbnail with the GitHub API info, can't see any way that helps that
- same API only gives the name of the person who did a release, not the repo owner, but admittedly that for our purposes is good enough indeed.

Finally, why should `*.info` files stay "simple"? After you write a 20000 line module, a few lines in the `*.info` file to ensure your project info is accurate shouldnt be a great burden, I'd say. They've always been simple because it wasnt necessary for Drupal, but we're aiming to be better, not same.

**Comment by jenlampton** [comment]
> would still be unable to have only one thumbnail with the GitHub API info, can't see any way that helps that

See https://github.com/backdrop/backdrop-issues/issues/1517

**Comment by xmacinfo** [comment]
> There is a rate limit on github API requests 5000/h

Why not switch to Gitlab?

https://about.gitlab.com/

**Comment by jenlampton** [comment]
> Why not switch to Gitlab?

Because it's not GitHub.

**Comment by serundeputy** [comment]
I did some work on this today. Add a field to the `project_module` node types called `download_count`.  

I have code to fetch the relevant data from the github API, but I need a github access token created by someone who owns the backdrop-contrib repo so that I can poll the API for the 200+ plus contrib projects nightly and populate the new field.

Once I have that I can put the field into the search view for the `/modules` page and expose a sort on that column.

Screenie:
![screen shot 2016-07-24 at 3 34 48 pm](https://cloud.githubusercontent.com/assets/6763671/17086017/30631ad6-51b5-11e6-89d7-07cd6c839b21.png)

**Comment by jenlampton** [comment]
Can you use the github API module? It already does the access token magic,
I think.

- - -
Jennifer Lea Lampton | twitter.com/jenlampton | 510-747-8230
Backdrop CMS & Drupal @ Jeneration Web Development
Check out my new website! | www.jeneration.com

On Sun, Jul 24, 2016 at 12:42 PM, Geoff St. Pierre <notifications@github.com

**Comment by serundeputy** [comment]
@jenlampton 

I could/can use the github API module, but the token for that is most likely stored in `settings.php` which is fine and good.  I need two things:

1.  The token has to be set up to have read access to the `backdrop-contrib` repo.  The github API module probably has access to `/backdrop/backdrop-issues` and maybe `backdrop/backdrop` if it has access to `backdrop-contrib` then we are good.

2.  If the github API token meets those criteria then I just need you to email me the token.  If it does not I need someone with admin to `backdrop-contrib` on github to create a token with read access to that repo and email it to me.

thanks,
~Geoff

**Comment by jenlampton** [comment]
I'm not really sure how to get you what you need. As a member of the security team, you should have access to backdrop-contrib. Can you find what you need in the UI?  I'm a bit lost as to where to set up tokens...

**Comment by serundeputy** [comment]
I've got the token I needed to authenticate to the github API as backdrop-contrib.

I've written a module to get the download data for each release and aggregate total downloads for modules, themes and layouts.  I've added a `field_download_count` to each of the content types `project_module`, `project_theme` and `project_layout` and the new module `borg_project_metrics` saves the download count for each project in that field for the node corresponding to the github project.

Layout node page:

![screen shot 2016-08-14 at 4 10 12 pm](https://cloud.githubusercontent.com/assets/6763671/17651665/c7b34390-6239-11e6-8d25-dc2b60a0c2d1.png)

Modules search page:

![screen shot 2016-08-14 at 4 12 28 pm](https://cloud.githubusercontent.com/assets/6763671/17651674/09455168-623a-11e6-8caa-2bcf365eed54.png)

I still need to scope the `hook_cron` to once daily say 2AM EST?

If this seems like a good course of action I can clean it up and make a `PR` anyone interested in taking on the front end theming?

thanks,
~Geoff

**Comment by jenlampton** [comment]
@serundeputy this is amazing!!!  I'd be happy to add the front-end theming as soon as you are ready :)

**Comment by serundeputy** [comment]
@jenlampton I've filed a `PR` at https://github.com/backdrop-ops/backdropcms.org/pull/284

It adds the `field_download_count` to the node types `project_module`, `project_theme` and `project_layout`.

It adds a new module `borg_project_metrics` the module polls github for downloads of each official release of a project and sums up a a total and populates the node fields.

I've updated the `/modules`, `/themes` and `/layouts` views to have the new field.

I think you can take it away for theming; I did not add filters to the views.

~Geoff

**Comment by jenlampton** [comment]
Oh, I see. it helps to read the whole comment :)  PR at #284 merged. Module `borg_project_metrics` enabled. @quicksketch wonders if this shouldn't be something that's merged upstream into `project_github` https://github.com/backdrop-contrib/project/tree/1.x-1.x/project_github ?

**Comment by jenlampton** [comment]
hm. Didn't mean to close that!

**Comment by jenlampton** [comment]
zomg: https://backdropcms.org/project/addanother

**Comment by serundeputy** [comment]
@jenlampton another `PR` to support getting downloads for the `core` node type.
https://github.com/backdrop-ops/backdropcms.org/pull/285
~Geoff

**Comment by jenlampton** [comment]
Whoops, closing prematurely :)
